name: c programming calculator project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: List files for debugging
      run: ls -la
       
    - name: Configure Cmake
      run: cmake -B build -S .
      
    - name: Build project
      run: cmake --build build
      
    - name: Run executable
      run: echo "1\n2\n3\nno" | ./calculator
    
