name: c programming calculator project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure Cmake
      run: cmake -B build -S .
      
    - name: Build project
      run: cmake --build .
      
    - name: Run executable
      run: ./calculator < input.txt
    
